### ISSUE TITLE
/write: Explain differences between "anonymous" and authored pads

### ISSUE THREAD

**Issue by fnwbr** [medienhaus/medienhaus-spaces#129]
# Problem

Typically you can create new Etherpads (which are publicly accessible as soon as someone knows the URL) or you can add existing pads from anywhere on the internet. (Again, just via their URL.)

As soon as you enable **MyPads** for a certain instance, the user gets two additional options: create new authored pads, and create authored pads with an additional password protection on top.

When showing the user all 4 options, they would list out like this:
- Create new "anonymous" pad
- Create new authored pad
- Create new password-protected pad
- Add existing pad via URL

Especially the difference between the first two options might be confusing.

# Solution

A possible solution may include
1. highlighting this difference between authored pads and "anonymous" pads by educating the user about it, and
2. still giving the user the option to choose between either

In both cases, this should include the upsides and downsides of each option. While authored pads focus on privacy and retain the ability for the user to -really- delete the pad and all of its contents irrevocably, the other option for anonymous pads might be better to use in group scenarios where you want the pad to outlive its original creator.

**Comment by aofn** [comment]
marked as stale since we changed the way we create new pads in #133
