### ISSUE TITLE
custom color values for the css variables in config.json or next.config.js

### ISSUE THREAD

**Issue by robertschnuell** [medienhaus/medienhaus-spaces#172]

**Comment by aofn** [comment]
we have variables in the css file
https://github.com/medienhaus/medienhaus-spaces/blob/ee3c2a73c7da42ef6d0dbee888fd097d4bc8f612/assets/_globalCss.css#L7-L30

and again from line 50-69 for dark mode.
Maybe that will do for now?
Having the colours in config.js could be a bigger change, and i think we would have to inject them or change a lo tof things around again, especially with tailwind and shadcn as well.

**Comment by robertschnuell** [comment]
yeah I know that we have this in the css, just if someone would like to set up a /spaces  instance and individualize the theme, for now they would have to fork the repository and aren't upstream compatible anymore. That was the origin of that idea to somehow get it into the config file which is not part of the upstream repository.

**Comment by aofn** [comment]
I think it's very unlikely we'll touch the colour variables any time soon, so it is probably upstream compatible for the foreseeable future 😁
#173 is the only way I can think of doing this atm, without actually introducing theming, or without using css injections or similar approaches.  
I don't know if this is a massive improvement to the current state.
