### ISSUE TITLE
Make use of `m.space.parent` event

### ISSUE THREAD

**Issue by fnwbr** [medienhaus/medienhaus-spaces#21]
Looks like Element is creating a `m.space.parent` event inside a "child" room of a certain space:
<img width="814" alt="image" src="https://github.com/medienhaus/medienhaus-spaces/assets/706419/beaf3fa5-e408-446f-8e29-ce207e344ade">

https://github.com/matrix-org/matrix-react-sdk/blob/161e19dfb6535081bb49bd992b0a452615f9bd45/src/utils/space.tsx#LL54C1-L61C4

### Problem

We probably want to adhere to what Element is doing and do the same when we create (sub-)spaces.

### Solution

Create those events when using our `addSpaceChild()` et al. methods.

**Comment by robertschnuell** [comment]
well yeah we had this discussion from time to time in the past years. That also for the CMS something like this is necessary, as it is noticeable what the original children of a space are but not the other way round what the origin assigned parent of the space is, when it was initial created by the author. And not just 'quoted' by another user in a different space. So as far as I understand this roughly what element is doing there, is coming across with a unified solution for this problem. To name the original parent of a space (correct me if I am wrong here in my understanding of this feature). 
If it is this case we should adopt it, as it is on our roadmap at some point anyway, but we did not set priority on it for now.
